/6
bednardev/T0d0List pull request #20
Opened 2023-04-20 15:10 UTC by bednardev

2023-04-20 22:09 UTC, kaufdev requested changes

2023-04-20 22:09 UTC, kaufdev commented on src/main/java/com/todolist/controllers/ToDoController.java
> +@GetMapping
Popraw formatowanie kodu to bo tu się rozjechało wszystko. 

Wejdz w ustawienia Intellij i poszukaj takiej pozycji jak jest otwarta na obrazku poniżej. Naciśniej "Reformat code". Dzięki temu za każdym savowaniem kodu (a intellij robi to w miarę często), kod twój zostanie z reformatowany do ustawien intellij, które zazwyczaj są spoko :D

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/20608418/233497114-537ccfcf-ab49-4f2f-995e-ab80d4cff1e0.png">

2023-04-20 22:09 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +    public List<Task> getTasks(Color color, String title) {
Dodałem komentarze do PR nr. 5, które zmienią tą metodę. To dodam komentarz tylko do jednej linijki, bo resztę się zmieni.

2023-04-20 22:09 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +                return taskStream.filter(c -> c.getTitle().contains("Roman")).
"Roman" to był bodajże tylko przykład. To ma działać tak:
Jak title z paramsów ma jakaś wartość, to zwrotka ma zawierać wszystie tytuły któr zawierają w sobie tą wartość z paramsów

2023-04-20 23:06 UTC, kaufdev requested changes

2023-04-20 23:06 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +                taskStream = taskStream.filter(c -> c.getTitle().contains("Roman"));
ten kod nie obsluzy sytuacji kiedy tylko title ma wartosc w parametrze.

2023-04-24 11:30 UTC, bednardev reviewed
Comments resolved

2023-04-24 20:13 UTC, kaufdev requested changes

2023-04-24 20:13 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +        if (color != null) {
Przerób na jednolevelowe ify

2023-04-25 07:27 UTC, bednardev reviewed
PR Resolved

2023-04-25 08:50 UTC, kaufdev approved these changes

2023-04-25 08:50 UTC, merged