feature/18 implemented
bednardev/T0d0List pull request #31
Opened 2023-05-08 10:05 UTC by bednardev

2023-05-08 21:33 UTC, kaufdev requested changes

2023-05-08 21:33 UTC, kaufdev commented on src/main/java/com/todolist/controllers/ToDoController.java
> +        taskToUpdate.setTitle(taskDtoToUpdate.getTitle());
logika związana z setowaniem powinna być raczej na pewno w repozytorium

2023-05-08 21:33 UTC, kaufdev commented on src/main/java/com/todolist/controllers/ToDoController.java
> +    @PutMapping
Zazwyczaj powinno się dawać id w adresie przy PUT

2023-05-08 21:33 UTC, kaufdev commented on src/main/java/com/todolist/controllers/ToDoController.java
> +    public Task updateTask(@RequestBody TaskDto taskDtoToUpdate) {
Tutaj jak i w patchu powinno być zwrócone TaskDto

2023-05-15 12:36 UTC, bednardev reviewed
Changes introduced according to review

2023-05-16 07:43 UTC, kaufdev requested changes

2023-05-16 07:43 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +                stream().
Zobacz ze findFirst() zwraca Optionala. Wywal .stream().findFirst() i zastosuje .map() bezposrednio na metodzie patchTask() ktora zwraca Optionala

2023-05-16 07:43 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +                stream().
To samo jak wyżej - zastosuj map() bezposrednio na metodzie

2023-05-16 07:43 UTC, kaufdev commented on src/main/java/com/todolist/controllers/ToDoController.java
> +    public TaskDto updateTask(@RequestBody Task taskToUpdate, @PathVariable Long id) {
zamień Task na TaskDTO. Task powinien byc tylko w serwisach i repo. Robi sie tak aby przy wiekszym skomplikowaniu kodu DTO mialo logike serializacji/deseruializacji (np. jakies adnotacji z biblioteki Jackson) a encja miała tylko adnotacje hibernatowe/spring-datowe

2023-05-16 08:03 UTC, bednardev reviewed
changes implemented

2023-05-16 08:12 UTC, kaufdev approved these changes

2023-05-16 08:12 UTC, merged