feature/19 implemented
bednardev/T0d0List pull request #33
Opened 2023-05-17 17:21 UTC by bednardev

2023-05-17 19:59 UTC, kaufdev requested changes

2023-05-17 19:59 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +        Optional<Task> taskOptional = taskRepository.findById(id);
Zmiast tej całej ciężkiej logiki poniżej, można to prościej zrobić wykorzystując to że spring pod metodą save(), sam sobie te setTitle() itp. 
1. Najpeirw musisz sprawdzić czy taki task istnieje (co robisz za pomocą findById()
2. Potem po prostu musisz taskToUpdate wsadzić do save. Powinno się to automatycznie wszystko zupdatować. To możesz zrobić w metodzie map() na wyniki findByID(). 
3. Zmapuj wynik save() na TaskDTO. 

Punkty 2 i 3 trzeba zrobić w chainie Optionalowym. save w map() i zmapkowanie tez map.

2023-05-17 19:59 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +        Optional<Task> taskOptional = taskRepository.findById(id);
Weź to przepisz na zrobienie łańcucha Optionalowego, który zaczyna się na findById, potem w map() dajesz logiki z setami (cala ta logika przeniesiona do innej prywatnej metody), a potem w nastepnym map() mapping do TaskDto

2023-05-17 19:59 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +        taskRepository.deleteById(id);
potestowałem i da się usunąć jakikolwiek id nawet jeśli nie istnieje. Według standarrdu REST powinno wtedy się wysłać 404.

2023-05-17 19:59 UTC, kaufdev commented on src/main/java/com/todolist/models/Task.java
>      public void setCreatedAt(Instant createdAt) {
nie działa zapisywanie na bazce tych datek. Ani przy save, ani przy update

2023-05-17 19:59 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +            taskStream = taskStream.filter(c -> c.getColor().equals(color));
Użycie metody filter() to było dla Ciebie treninigiem zebys sie nauczyl na streamach robic przed bazką.

W realnym życiu nie robi się takich filtrów przy zapytaniach na bazke. Bazka moze miec 400k rekordow (a to w sumie malo) i taki filtr juz potrafi zamulic. Jedno zapytanie do bazy danych zrobi to duzo szybciej. 

Wiec w jakis sposob musisz polaczyc te ify z tym zeby metoda wewnatrz ifa zmieniala forme zapytania do bazki zamiast zmieniala juz gotowe wyniki z bazki.

To jest ciezki, aczykolwiek wazny i interesujecy temat, wiec jak chcesz mozemy to na nastepnego PR wrzucic

2023-05-19 10:56 UTC, bednardev commented on src/main/java/com/todolist/services/TaskService.java
> +            taskStream = taskStream.filter(c -> c.getColor().equals(color));
Resolved without filtering by single word of title (entire title required)

2023-05-21 21:28 UTC, kaufdev requested changes

2023-05-21 21:28 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +        taskToSave.setCreatedAt(Instant.now());
Robisz to ręcznie. Powinno się to zcedować na Spring Data, który to zrobi za Ciebie z dokładnym timestamepem ( to też dotyczy lastUpdated pola). https://www.baeldung.com/database-auditing-jpa i punkt 4 w tym artykule

2023-05-21 21:28 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +        Task taskToUpdate = new Task(id, taskRepository.findById(id).get().getCreatedAt(), taskDtoToUpdate.getTitle(), taskDtoToUpdate.getDescription(), Color.valueOf(taskDtoToUpdate.getColor()));
jak zrobisz te adnotacje z JPA co do pól audytowych to to będzie prostsze bo nie będziesz potrzebował repo.findById tutaj.

2023-05-21 21:28 UTC, kaufdev commented on src/main/java/com/todolist/services/TaskService.java
> +        if (color != null & title != null)
jak wpiszesz kolor malymi literami to leci 400 a powinno przejść

2023-05-24 14:45 UTC, kaufdev requested changes

2023-05-25 08:31 UTC, kaufdev approved these changes

2023-05-25 08:31 UTC, merged